name: Push GompeiLib

on:
  release:
    types: [published]

jobs:
  sync:
    uses: Team-190/CI-Workflows/.github/workflows/syncgompeilib.yml@main
    with:
      direction: push
    secrets:
      GOMPEILIB_SYNC: ${{ secrets.GOMPEILIB_SYNC }}